export const actionTypes = {
  SET_USERNAME: "SET_USERNAME",
  SET_FITNESS_DATA: "SET_FITNESS_DATA",
  CLEAR_DATA: "CLEAR_DATA",
  SET_WORKOUTS: "SET_WORKOUTS",
  SET_AUTH_DATA: "SET_AUTH_DATA",
  SET_TODAYS_WORKOUT: "SET_TODAYS_WORKOUT",
};
